name: store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  custom_navigator: ^0.3.0
  dio: ^5.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  provider: ^6.0.5
  shimmer: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - lib/configs/
  